services:
  nats:
    image: nats:2.11
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data

  dapr_placement:
    image: "daprio/placement"
    command: ["./placement", "--port", "50005"]
    ports:
      - "50005:50005"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
      - GF_METRICS_ENABLED=true
      - GF_METRICS_BASIC_AUTH_USERNAME=admin
      - GF_METRICS_BASIC_AUTH_PASSWORD=admin
    volumes:
      - ./infra/grafana:/var/lib/grafana
    ports:
      - "3001:3000"

  nats_exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: ["-varz", "http://nats:8222"]
    ports:
      - "7777:7777"
    depends_on:
      - nats

  # Example agent (you’ll scale this out per-agent)
  agent_hello:
    build:
      context: ./agents/agent_hello
      dockerfile: Dockerfile
    environment:
      - DAPR_APP_ID=agent-hello
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    ports:
      - "8000:8000" # Application port
      - "3500:3500" # Dapr HTTP port
    depends_on:
      - nats
      - dapr_placement
      - nats_exporter
      - prometheus
      - grafana
      
volumes:
  nats-data:
