apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-nats
  namespace: default
spec:
  type: pubsub.nats
  version: v1
  metadata:
  - name: natsURL
    value: "nats://nats:4222"
  - name: durable
    value: "true"
  - name: startAt
    value: "lastReceived"
